name: Deploy React Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: 
          cd ~/react-flask-app-Deployment

          git pull origin main

          export NODE_OPTIONS=--openssl-legacy-provider

          yarn install
          yarn build

          sudo systemctl restart flaskapp
          sudo systemctl restart nginx
